"""empty message

Revision ID: 8dbc6a5ae051
Revises: 
Create Date: 2025-12-08 19:48:01.274735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbc6a5ae051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('artwork_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=225), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('favorite_pokemon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_pokemon_id'), ['pokemon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_pokemon_id'))

    op.drop_table('favorite')
    op.drop_table('users')
    op.drop_table('pokemons')
    # ### end Alembic commands ###
